name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: bpi-f3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -B build -DBUILD_TESTS=1 -DBUILD_THUNKING=1 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build -j8
      - name: Test
        run: |
          FELIX86_ALL_EXTENSIONS=g,v,b ./build/felix86_test
          ./build/felix86 -k
          FELIX86_ALL_EXTENSIONS=g,v ./build/felix86_test
          ./build/felix86 -k
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact
          mkdir -p ./artifact/lib
          cp ./build/felix86 ./artifact/
          cp ./src/felix86/hle/guest_libs/libGL.so.1 ./artifact/lib/
          cp ./src/felix86/hle/guest_libs/libEGL.so.1 ./artifact/lib/
          cp ./src/felix86/hle/guest_libs/libGLX.so.0 ./artifact/lib/
          cp ./src/felix86/hle/guest_libs/libvulkan.so.1 ./artifact/lib/
          cp ./src/felix86/hle/guest_libs/libwayland-client.so ./artifact/lib/
          cp ./src/felix86/hle/guest_libs/libluajit-5.1.so ./artifact/lib/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Linux executable
          path: ./artifact/
